import './globals.scss'
import Head from 'next/head'
import apple from "@/fav-icons/apple-touch-icon.png"
import fav32 from "@/fav-icons/favicon-32x32.png"
import fav16 from "@/fav-icons/favicon-16x16.png"

export const metadata = {
  title: 'Hassaam Hassaan Engineering',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="apple-touch-icon" sizes="180x180" href={apple} />
        <link rel="icon" type="image/png" sizes="32x32" href={fav32} />
        <link rel="icon" type="image/png" sizes="16x16" href={fav16} />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <body >{children}</body>
    </html>
  )
}
